id: I9FFD7014
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T06:39:23+00:00'
last_modified: '2022-06-07T17:01:53.868764+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6055
  title: སློབ་གྲྭ་ཆེན་མོའི་བོད་ཡིག་སློབ་དེབ་ཤར་གངས་རི་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4C4C:
      image_group_id: I1KG9314
      title: ''
      total_pages: 736
      order: 1
      base_file: 4C4C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
