id: P003016
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:34:31.978125
source_metadata:
  id: bdr:W1KG6055
  title: སློབ་གྲྭ་ཆེན་མོའི་བོད་ཡིག་སློབ་དེབ་ཤར་གངས་རི་མ།
  author: ''
  volumes:
    457e4ee7c6604a67abd3eefbbd282f4f:
      image_group_id: I1KG9314
      title: ''
      volume_number: 1
      total_pages: 736
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
